---
name: Validate Plugin

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.4', '8.0', '8.1', '8.2']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: >
            dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite,
            pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Validate composer.json
        run: composer validate

      - name: Check PHP syntax
        run: |
          find . -name "*.php" -not -path "./vendor/*" -print0 | \
            xargs -0 -n1 php -l

      - name: Install dependencies
        run: composer install --no-progress --no-suggest

      - name: Test dependency detection
        run: |
          cat > test_deps.php << 'EOF'
          <?php
          define('ABSPATH', '/tmp/');
          define('YHT_PLUGIN_FILE', __DIR__ . '/your-hidden-trip-planner.php');
          define('YHT_PLUGIN_PATH', __DIR__ . '/');
          function add_action() {}
          function register_activation_hook() {}
          function register_deactivation_hook() {}
          require __DIR__ . '/includes/class-yht-plugin.php';
          $plugin = YHT_Plugin::get_instance();
          $reflection = new ReflectionClass($plugin);
          $method = $reflection->getMethod('has_vendor_dependencies');
          $method->setAccessible(true);
          $has_deps = $method->invoke($plugin);
          if (!$has_deps) {
            echo 'FAIL: Dependencies not detected after composer install' . PHP_EOL;
            exit(1);
          }
          echo 'SUCCESS: Dependencies correctly detected' . PHP_EOL;
          EOF
          php test_deps.php
